CREATE TABLE plants (
    id BIGSERIAL PRIMARY KEY,
    external_id UUID NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL,
    identifications JSONB NOT NULL,
    display_name VARCHAR(255),
    species VARCHAR(255),
    cultivar VARCHAR(255),
    health_status JSONB NOT NULL,
    care_instructions JSONB NOT NULL,
    difficulty VARCHAR(50) NOT NULL,
    toxicity JSONB NOT NULL,
    images JSONB NOT NULL,
    temp_identity_id UUID,
    last_watered VARCHAR(50),
    soil_moisture VARCHAR(50),
    repotted_since_buying VARCHAR(50),
    light_location VARCHAR(50),
    near_heat_or_ac VARCHAR(50),
    last_watering_date DATE,
    last_fertilization_date DATE,
    last_repotting_date DATE,
    last_status_update_date DATE
);
