ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.github.kperczynski.KtorFrameApplicationServerKt.configureServer

database:
  url: jdbc:postgresql://localhost:5432/ktordb
  user: ktor
  password: ktorpassword
  driver: org.postgresql.Driver
