package io.github.kperczynski.libs.problemdetail

import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty

/**
 * RFC 7807 Problem Details for HTTP APIs
 * https://datatracker.ietf.org/doc/html/rfc7807
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
data class ProblemDetail(
    /**
     * A URI reference that identifies the problem type.
     * It should provide human-readable documentation for the problem type.
     */
    @param:JsonProperty("type")
    val type: String = "about:blank",

    /**
     * A short, human-readable summary of the problem type.
     * It SHOULD NOT change from occurrence to occurrence of the problem.
     */
    @param:JsonProperty("title")
    val title: String,

    /**
     * The HTTP status code generated by the origin server.
     */
    @param:JsonProperty("status")
    val status: Int,

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    @param:JsonProperty("detail")
    val detail: String? = null,

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    @param:JsonProperty("instance")
    val instance: String? = null,

    /**
     * Extension members for additional domain-specific details.
     * Jackson will serialize this as a flat map alongside other fields.
     */
    @param:JsonProperty("extension_data")
    val extensionData: Map<String, Any>? = null
)